"""update user model

Revision ID: 09f391309519
Revises: f225b2ed55ae
Create Date: 2025-10-22 09:25:57.139248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f391309519'
down_revision: Union[str, Sequence[str], None] = 'f225b2ed55ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('municipalities', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index('ix_municipality_district_id', 'municipalities', ['district_id'], unique=False)
    op.create_unique_constraint('uq_municipality_name_per_district', 'municipalities', ['name', 'district_id'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('users_district_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_ward_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_municipality_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'wards', ['ward_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'district_id')
    op.drop_column('users', 'municipality_id')
    op.add_column('wards', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index('ix_ward_municipality_id', 'wards', ['municipality_id'], unique=False)
    op.create_unique_constraint('uq_ward_number_per_municipality', 'wards', ['ward_number', 'municipality_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ward_number_per_municipality', 'wards', type_='unique')
    op.drop_index('ix_ward_municipality_id', table_name='wards')
    op.drop_column('wards', 'is_active')
    op.add_column('users', sa.Column('municipality_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_municipality_id_fkey'), 'users', 'municipalities', ['municipality_id'], ['id'])
    op.create_foreign_key(op.f('users_ward_id_fkey'), 'users', 'wards', ['ward_id'], ['id'])
    op.create_foreign_key(op.f('users_district_id_fkey'), 'users', 'districts', ['district_id'], ['id'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_municipality_name_per_district', 'municipalities', type_='unique')
    op.drop_index('ix_municipality_district_id', table_name='municipalities')
    op.drop_column('municipalities', 'is_active')
    op.drop_column('districts', 'is_active')
    # ### end Alembic commands ###
