"""Recreate role column as ENUM

Revision ID: 1834e183a061
Revises: 09f391309519
Create Date: 2025-10-23 13:11:15.141646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1834e183a061'
down_revision: Union[str, Sequence[str], None] = '09f391309519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum(
        'citizen', 'official', 'mayor', 'super_admin',
        name='user_role_enum'
    )
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column('role', user_role_enum, nullable=False, server_default='citizen')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role_enum = sa.Enum(
        'citizen', 'official', 'mayor', 'super_admin',
        name='user_role_enum'
    )
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
