"""update department

Revision ID: 3b1b6a20689b
Revises: deed64c2494a
Create Date: 2025-10-26 15:21:40.335980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1b6a20689b'
down_revision: Union[str, Sequence[str], None] = 'deed64c2494a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('complaints_municipality_id_fkey'), 'complaints', type_='foreignkey')
    op.drop_constraint(op.f('complaints_ward_id_fkey'), 'complaints', type_='foreignkey')
    op.drop_constraint(op.f('complaints_district_id_fkey'), 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'wards', ['ward_id'], ['id'], ondelete='SET NULL')
    op.drop_column('complaints', 'district_id')
    op.drop_column('complaints', 'municipality_id')
    op.alter_column('users', 'department',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('complaints', sa.Column('municipality_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(op.f('complaints_district_id_fkey'), 'complaints', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(op.f('complaints_ward_id_fkey'), 'complaints', 'wards', ['ward_id'], ['id'])
    op.create_foreign_key(op.f('complaints_municipality_id_fkey'), 'complaints', 'municipalities', ['municipality_id'], ['id'])
    # ### end Alembic commands ###
