"""Add default values to complaints tables

Revision ID: f225b2ed55ae
Revises: d98014673ae3
Create Date: 2025-10-21 09:27:07.428869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f225b2ed55ae'
down_revision: Union[str, Sequence[str], None] = 'd98014673ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'urgency',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('complaints', 'current_status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'current_status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('complaints', 'urgency',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
